volumes:
  yd_files_local_postgres_data: {}
  yd_files_local_postgres_data_backups: {}


services:
  django:
    build:
      context: yd_files
      dockerfile: compose/local/django/Dockerfile
    image: yd_files_local_django
    container_name: yd_files_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: yd_files
      dockerfile: compose/production/postgres/Dockerfile
    image: yd_files_production_postgres
    container_name: yd_files_local_postgres
    volumes:
      - yd_files_local_postgres_data:/var/lib/postgresql/data
      - yd_files_local_postgres_data_backups:/backups
    env_file:
      - .envs/.local/.postgres
